version: "3.4"
services:
 registration:
  image: jasdhali/cust-commerce-registry-server:1.0.0
  ports:
   - "9761:9761"

 gateway:
  image: jasdhali/cust-commerce-api-gateway:1.0.0
  ports:
   - "9080:9080"
  links:
   - registration
  environment:
   - JAVA_OPTS=
     -DEUREKA_URI=http://registration:8761/eureka
  depends_on:
   - registration

 security:
  image: jasdhali/cust-commerce-jwt-security:1.0.0
  ports:
   - "8082:8082"
  links:
   - registration
  environment:
   - JAVA_OPTS=
     -DEUREKA_URI=http://registration:8761/eureka     
     #- spring.datasource.url=jdbc:mysql://mysqldb:3306/spring_security
     #- spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
  depends_on:
   #- mysqldb
   - registration

 onboarding:
  image: jasdhali/cust-commerce-user-onboarding:1.0.0
  ports:
   - "9081:9081"
  links:
   - registration
  environment:
   - JAVA_OPTS=
     -DEUREKA_URI=http://registration:8761/eureka
  depends_on:   
   - registration   
   

  
   
